site_name: Matas Vitkauskas' Handover Doc
nav:
  - Home: index.md
  - About: about.md
  - PD: Projects/PD.md
  - GBM: Projects/GBM.md
  - Smchd1: Projects/Smchd1.md
  - Masmr: Projects/Masmr.md
  - Slides: Slides.md
theme: flatly

plugins:
  - search